[package]
name = "RustHelloWorld"
version = "0.1.0"
authors = ["kdw9502 <kdw9502@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
